[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python run.py server"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 120
restartPolicyType = "always"
restartPolicyMaxRetries = 10
